apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.tlsSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.webhook.service.name }}.{{ .Release.Namespace }}.svc
    - {{ .Values.webhook.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  secretName: {{ .Values.webhook.tlsSecretName }}
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.webhook.service.name }}.{{ .Release.Namespace }}.svc

