apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.webhookName }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.webhook.tlsSecretName }}
webhooks:
  - name: {{ .Values.webhook.webhookName }}
    clientConfig:
      service:
        name: {{ .Values.webhook.service.name }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.webhook.webhookPath }}
        port: {{ .Values.webhook.service.port }}
    rules:
      - apiGroups: ["{{ .Values.webhook.group }}"]
        apiVersions: ["{{ .Values.webhook.version }}"]
        operations: ["CREATE", "UPDATE"]
        resources: ["{{ .Values.webhook.resource }}"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
