apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cert-manager
  ports:
    - port: 9402
      targetPort: 9402
      name: http

